#!/usr/bin/env python3
"""
Thumbnails for the dish and staple squares, and the imagery.js block that names them.

WHY THIS EXISTS. The squares ship at 880x880 (40-110 KB) because a slide-over panel shows
them large. The card grid shows the same picture at 80px. Serving the 880px file into an
80px box is a 7x waste that is completely invisible - the page looks right, it is just four
times heavier than it needs to be, and nothing in the build would ever complain.

So: one 176px derivative each (2x for a 88px box), and imagery.js carries BOTH, with the
component reading `thumb ?? src`. The fallback matters - if this script has not been run,
the grid still renders correctly, just heavy. It degrades in bytes, not in pixels.

    python scripts/make_thumbs.py           # build thumbs, print the JS block
    python scripts/make_thumbs.py --emit    # also write src/data/imagery.generated.js
"""
from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "public" / "img"
GEN = ROOT / "src" / "data" / "imagery.generated.js"

# TWO derivatives, because two grids draw these at very different sizes and one file
# cannot serve both without waste at one end or blur at the other.
#   thumb  88px in the dish grid  -> 176px covers 2x
#   card   up to 150px tall and ~260px wide in the Pantry plate grid -> 420px covers 2x
# Serving the 176px thumb into the plate card was the bug: upscaled on every display and
# visibly soft on a retina one.
THUMB = 176
CARD = 420
MAX_KB = 250


def _resize(src: Image.Image, longest: int, dest) -> tuple[int, int, int]:
    w, h = src.size
    im = src
    scale = longest / max(w, h)
    if scale < 1:
        im = src.resize((round(w * scale), round(h * scale)), Image.LANCZOS)
    for q in (78, 70, 62):
        im.save(dest, "WEBP", quality=q, method=6)
        if dest.stat().st_size <= MAX_KB * 1024:
            break
    return im.width, im.height, dest.stat().st_size


def build() -> list[dict]:
    rows = []
    for p in sorted(OUT.glob("*.webp")):
        if not p.stem.startswith(("dish-", "staple-")):
            continue
        if p.stem.endswith(("-thumb", "-card")):
            continue
        src = Image.open(p).convert("RGB")
        tw, th, tb = _resize(src, THUMB, OUT / f"{p.stem}-thumb.webp")
        cw, ch, cb = _resize(src, CARD, OUT / f"{p.stem}-card.webp")
        rows.append(dict(stem=p.stem, tw=tw, th=th, tb=tb, cw=cw, ch=ch, cb=cb))
    return rows


def js_block(rows) -> str:
    """Emit dishArt / stapleArt keyed on the DATA slug, not the file slug.

    The prefix is stripped deliberately: `dish-lamb-and-beet-stew-tuhu.webp` is keyed as
    `lamb-and-beet-stew-tuhu`, which is what recipes.js calls it. Keying on the filename
    would force every call site to know the prefix, and the first time a dish and a staple
    shared a name it would silently collide.
    """
    def entries(prefix):
        out = []
        for r in rows:
            stem = r["stem"]
            if not stem.startswith(prefix):
                continue
            slug = stem[len(prefix):]
            full = Image.open(OUT / f"{stem}.webp")
            out.append(
                f"  '{slug}': {{\n"
                f"    src: '/img/{stem}.webp',\n"
                f"    thumb: '/img/{stem}-thumb.webp',\n"
                f"    card: '/img/{stem}-card.webp',\n"
                f"    w: {full.width}, h: {full.height},\n"
                f"    tw: {r['tw']}, th: {r['th']}, cw: {r['cw']}, ch: {r['ch']},\n"
                f"    alt: '',\n"
                f"  }},"
            )
        return "\n".join(out)

    return (
        "// GENERATED by scripts/make_thumbs.py — do not hand-edit.\n"
        "// Regenerate:  python scripts/make_thumbs.py --emit\n"
        "//\n"
        "// The square painted plates, keyed on the slug the DATA uses (no file prefix).\n"
        "// `src` is the full 880px plate for a panel. `thumb` is 176px, for the dish grid\n"
        "// at 88px. `card` is 420px, for the Pantry plate grid, which draws up to 150px\n"
        "// tall on a card up to ~260px wide — serving the 176px thumb there upscaled it\n"
        "// and looked soft on any retina screen. Components read the size they need\n"
        "// `?? src`, so a missing derivative costs bytes rather than correctness.\n"
        "//\n"
        "// alt is deliberately EMPTY. In every placement these sit directly beside the dish\n"
        "// name and its concept line, so describing the picture would make a screen reader\n"
        "// say the same thing twice. Decorative here, by construction.\n\n"
        "export const dishArt = {\n" + entries("dish-") + "\n}\n\n"
        "export const stapleArt = {\n" + entries("staple-") + "\n}\n"
    )


def main() -> None:
    if not OUT.is_dir():
        sys.exit("public/img missing - run process_images.py first")
    rows = build()
    if not rows:
        sys.exit("no dish-*/staple-* plates found")
    tt = sum(r["tb"] for r in rows)
    ct = sum(r["cb"] for r in rows)
    full = sum((OUT / f"{r['stem']}.webp").stat().st_size for r in rows)
    print(f"{len(rows)} subjects: {tt // 1024} KB of thumbs + {ct // 1024} KB of cards "
          f"(full plates would be {full // 1024} KB)")
    over = [r["stem"] for r in rows if max(r["tb"], r["cb"]) > MAX_KB * 1024]
    if over:
        sys.exit(f"over budget: {over}")

    if "--emit" in sys.argv:
        GEN.write_text(js_block(rows), encoding="utf-8")
        print(f"wrote {GEN.relative_to(ROOT)}")
    else:
        print("\n(pass --emit to write src/data/imagery.generated.js)")


if __name__ == "__main__":
    main()
